version: "3.8"
services:
  todo:
    build: .
    environment:
      HTTP_SERVER__ADDR_PORT: 0.0.0.0:8080
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
