name: Go

on:
  push:
    branches:
      - main
      - develop
      - ci/**
    tags:
      - "v*"

  pull_request:
    paths:
      - .github/**
      - cmd/**
      - internal/**
      - pkg/**
      - go.mod
      - go.sum
  workflow_dispatch:

concurrency:
  group: go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: |
          if ! command -v git &> /dev/null
          then
            sudo apt update
            sudo apt install -y --no-install-recommends \
              git
          fi

      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run go mod tidy
        run: |
          go mod tidy -v
          git diff --exit-code

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          only-new-issues: ${{ github.event_name == 'pull_request' }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - go-mod-tidy
      - golangci-lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Build
        run: go install ./...
